#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 6.0.1
#  in conjunction with Tcl version 8.6
#    Jan 26, 2021 11:01:12 AM CET  platform: Darwin

import sys
import urllib.request, urllib.parse, urllib.error
import json
import config_file

config_file_name="config.priv"

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top
    try:
        ip,port = config_file.config_file_readIP_Port(config_file_name)
        w.Entry1.insert(0, ip)
        w.Entry2.insert(0, port)
    except:
        print('e005d')

def click_connect(p1):
    allobjects_list = list()
    try:
        ip = w.Entry1.get()
        port = w.Entry2.get()
        urldata = 'http://'+ip+':'+port+'/api/v1/resources/demo_content/all'
    except:
        w.Scrolledlistbox1.insert(0, "Error while connecting")
    try:  
      webURL = urllib.request.urlopen(urldata)
      data = webURL.read()
      json_object = json.loads(data.decode('utf-8'))
      try:
        for key in json_object:
          allobjects_list.append(key)
      except:
        print('e006f')
    except:
        w.Scrolledlistbox1.insert(0, "Connection failed!")
        print("connection failed - get_allobjects_in_a_list")
    i = -1
    for item in allobjects_list:
        i = i+1
        w.Scrolledlistbox1.insert(i, item)
    #write config file
    config_file.config_file_create(config_file_name)
    try:
        conf_ip,conf_port = config_file.config_file_readIP_Port(config_file_name)
        if conf_ip != ip or None:
            config_file.writeIPPort_configfile(config_file_name,ip,port)
    except:
        print("e_08t")

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import Client
    Client.vp_start_gui()




